CREATE SCHEMA listaflora;


SET search_path = listaflora, pg_catalog;

SET default_with_oids = false;



CREATE TABLE listaflora.LISTA_DA_FLORA_BRASIL (
    ID INTEGER  NOT NULL,
    TAXONID INTEGER NOT NULL,
    SCIENTIFICNAME TEXT,
    ACCEPTEDNAMEUSAGE TEXT,
    PARENTNAMEUSAGE TEXT,
    NAMEPUBLISHEDIN TEXT,
    NAMEPUBLISHEDINYEAR TEXT,
    HIGHERCLASSIFICATION TEXT,
    PHYLUM TEXT,
    CLASSNAME TEXT,
    ORDERNAME TEXT,
    FAMILYNAME TEXT,
    GENUS TEXT,
    SPECIFICEPITHET TEXT,
    INFRASPECIFICEPITHET TEXT,
    TAXONRANK TEXT,
    SCIENTIFICNAMEAUTHORSHIP TEXT,
    TAXONOMICSTATUS TEXT,
    NOMENCLATURALSTATUS TEXT,
    MODIFIED TEXT,
    BIBLIOGRAPHICCITATION TEXT,
    REFERENCIAS TEXT
);